server:
  port: ${SERVER_PORT:8881}
  servlet:
    encoding:
      charset: utf-8
      force: true
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  mvc:
    # Disable view resolution since the frontend will be served by React. The JSP view resolver can be removed once all JSPs are migrated.
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL:jdbc:mysql://team2-free-project-mysql-db.crwceg2wuy6s.ap-northeast-2.rds.amazonaws.com/greendb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${JPA_SHOW_SQL:false}
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE
  output:
    ansi:
      enabled: always
  security:
    debug: true

gemini:
  api:
    key:

  # Removed mybatis configuration since the project now uses Spring Data JPA

jwt:
  secret: ${JWT_SECRET:myScretKey0000fdafadsdfdsafdasffsafsafasfdfdfsdafafsasdyasdyasdasduasbdhafjkshfbahwefbakvbagkcvadsv}
  expiration: ${JWT_EXPIRATION:36000000}
